version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jiankai-postgres
    environment:
      POSTGRES_USER: jiankai
      POSTGRES_PASSWORD: jiankai123
      POSTGRES_DB: jiankai_quotation
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
